"""Quali app ridisegniamo e con quale simbolo (Material Symbols Rounded,
licenza Apache 2.0). Per le app con un marchio si usa un simbolo generico,
mai il logo: scelta di Michele, 07/10/2026.

Chiave: nome dell'icona nel pacchetto. Valore: (simbolo, [pacchetti]).
Il simbolo "STEMMA" vuol dire lo stemma del Club al posto del glifo."""

ICONE = {
    'telefono':     ('call',               ['com.google.android.dialer', 'com.samsung.android.dialer', 'com.android.dialer']),
    'contatti':     ('contacts',           ['com.google.android.contacts', 'com.samsung.android.app.contacts', 'com.android.contacts']),
    'messaggi':     ('sms',                ['com.google.android.apps.messaging', 'com.samsung.android.messaging', 'com.android.mms']),
    'fotocamera':   ('photo_camera',       ['com.google.android.GoogleCamera', 'com.sec.android.app.camera', 'com.android.camera2', 'com.android.camera']),
    'galleria':     ('photo_library',      ['com.sec.android.gallery3d', 'com.google.android.apps.photos', 'com.android.gallery3d']),
    'impostazioni': ('settings',           ['com.android.settings']),
    'orologio':     ('schedule',           ['com.sec.android.app.clockpackage', 'com.google.android.deskclock', 'com.android.deskclock']),
    'calendario':   ('calendar_month',     ['com.google.android.calendar', 'com.samsung.android.calendar', 'com.android.calendar']),
    'calcolatrice': ('calculate',          ['com.sec.android.app.popupcalculator', 'com.google.android.calculator', 'com.android.calculator2']),
    'file':         ('folder',             ['com.sec.android.app.myfiles', 'com.google.android.apps.nbu.files', 'com.google.android.documentsui']),
    'browser':      ('public',             ['com.android.chrome', 'com.sec.android.app.sbrowser', 'org.mozilla.firefox', 'com.brave.browser']),
    'posta':        ('mail',               ['com.google.android.gm', 'com.samsung.android.email.provider', 'com.microsoft.office.outlook']),
    'store':        ('shop',               ['com.android.vending']),
    'galaxy_store': ('storefront',         ['com.sec.android.app.samsungapps']),
    'mappe':        ('map',                ['com.google.android.apps.maps', 'com.waze']),
    'video':        ('smart_display',      ['com.google.android.youtube']),
    'cerca':        ('search',             ['com.google.android.googlequicksearchbox']),
    'meteo':        ('partly_cloudy_day',  ['com.sec.android.daemonapp', 'com.google.android.apps.weather']),
    'note':         ('edit_note',          ['com.samsung.android.app.notes', 'com.google.android.keep']),
    'registratore': ('mic',                ['com.sec.android.app.voicenote', 'com.google.android.apps.recorder']),
    'cloud':        ('cloud',              ['com.google.android.apps.docs', 'com.microsoft.skydrive']),
    'chat':         ('chat',               ['com.whatsapp', 'com.whatsapp.w4b']),
    'invia':        ('send',               ['org.telegram.messenger']),
    'foto_social':  ('camera',             ['com.instagram.android']),
    'gruppi':       ('groups',             ['com.facebook.katana']),
    'forum':        ('forum',              ['com.facebook.orca']),
    'musica_video': ('music_video',        ['com.zhiliaoapp.musically']),
    'cuffie':       ('headphones',         ['com.spotify.music']),
    'musica':       ('music_note',         ['com.google.android.apps.youtube.music', 'com.sec.android.app.music']),
    'film':         ('movie',              ['com.netflix.mediaclient', 'com.amazon.avod.thirdpartyclient', 'com.disney.disneyplus']),
    'cancelletto':  ('tag',                ['com.twitter.android']),
    'calcio':       ('sports_soccer',      ['com.dazn']),
    'carrello':     ('shopping_cart',      ['com.amazon.mShop.android.shopping']),
    'carta':        ('credit_card',        ['posteitaliane.posteapp.apppostepay', 'com.paypal.android.p2pmobile', 'com.satispay.customer']),
    'banca':        ('account_balance',    ['posteitaliane.posteapp.appbpol', 'com.latuabancaperandroid', 'it.ingdirect.app']),
    'documento':    ('badge',              ['it.pagopa.io.app', 'it.ipzs.cieid']),
    'portafoglio':  ('wallet',             ['com.google.android.apps.walletnfcrel', 'com.samsung.android.spay']),
    'salute':       ('favorite',           ['com.sec.android.app.shealth', 'com.google.android.apps.fitness']),
    'traduttore':   ('translate',          ['com.google.android.apps.translate']),
    'casa':         ('home',               ['com.samsung.android.oneconnect', 'com.google.android.apps.chromecast.app']),
    'treno':        ('train',              ['com.lynxspa.prontotreno', 'it.italotreno']),
    'auto':         ('directions_car',     ['com.ubercab']),
    'stemma':       ('STEMMA',             ['it.romaclubmatera.soci', 'it.romaclubmatera.verifica', 'it.romaclubmatera.tema']),
}
