"""App diffuse con la loro icona originale dentro la cornice del Club (scelta
di Michele, 09/10/2026: con Samsung Theme Park le app fuori dal pacchetto
restano originali). Le immagini in loghi/ vengono da personale/cornice.py.
I loghi restano dei rispettivi titolari: servono solo a riconoscere l'app
e sono esclusi dalla licenza CC BY (vedi LICENZA.md). Niente AS Roma, banche,
salute, lavoro, scommesse.

Chiave: nome del file in loghi/. Valore: componenti pacchetto/attivita'."""

LOGHI = {
    'adidas': ['com.adidas.app/com.adidas.app.SplashActivity'],
    'airbnb': ['com.airbnb.android/com.airbnb.android.feat.splashscreen.SplashScreenActivity'],
    'alexa': ['com.amazon.dee.app/com.amazon.dee.app.Launcher'],
    'claude': ['com.anthropic.claude/com.anthropic.claude.mainactivity.MainActivity'],
    'booking': ['com.booking/com.booking.startup.HomeActivity'],
    'decathlon': ['com.decathlon.app/com.decathlon.app.activities.main.ShoppingAppActivity'],
    'deepl': ['com.deepl.mobiletranslator/com.deepl.mobiletranslator.MainActivity'],
    'discord': ['com.discord/com.discord.main.MainDefault'],
    'ebay': ['com.ebay.mobile/com.ebay.mobile.home.impl.main.MainActivity'],
    'temu': ['com.einnovation.temu/com.baogong.splash.activity.MainFrameActivity'],
    'authenticator': ['com.google.android.apps.authenticator2/com.google.android.apps.authenticator2.main.MainActivity'],
    'gemini': ['com.google.android.apps.bard/com.google.android.apps.bard.shellapp.BardEntryPointActivity'],
    'documenti': ['com.google.android.apps.docs.editors.docs/com.google.android.apps.docs.app.NewMainProxyActivity'],
    'fogli': ['com.google.android.apps.docs.editors.sheets/com.google.android.apps.docs.app.NewMainProxyActivity'],
    'presentazioni': ['com.google.android.apps.docs.editors.slides/com.google.android.apps.docs.app.NewMainProxyActivity'],
    'google_chat': ['com.google.android.apps.dynamite/com.google.android.apps.dynamite.startup.StartUpActivity'],
    'family_link': ['com.google.android.apps.kids.familylink/com.google.android.apps.kids.familylink.flutter.standalone.HomeActivity'],
    'meet': ['com.google.android.apps.tachyon/com.google.android.apps.tachyon.MainActivity'],
    'google_tv': ['com.google.android.videos/com.google.android.videos.GoogleTvEntryPoint'],
    'ikea': ['com.ingka.ikea.app/com.ingka.ikea.app.splash.FirstEntryActivity'],
    'threads': ['com.instagram.barcelona/com.instagram.barcelona.mainactivity.BarcelonaActivity'],
    'lidl': ['com.lidl.eci.lidlplus/es.lidlplus.i18n.StandardLauncher'],
    'linkedin': ['com.linkedin.android/com.linkedin.android.authenticator.FallFestivalActivityAlias'],
    'office': ['com.microsoft.office.officehubrow/com.microsoft.office.officesuite.OfficeSuiteActivity'],
    'teams': ['com.microsoft.teams/com.microsoft.skype.teams.Launcher'],
    'klarna': ['com.myklarnamobile/com.klarna.LaunchActivity'],
    'nike': ['com.nike.omega/com.nike.omega.MainActivityDefault'],
    'chatgpt': ['com.openai.chatgpt/com.openai.chatgpt.MainActivity'],
    'trova_dispositivo': ['com.samsung.android.app.find/com.samsung.android.app.find.MainActivity'],
    'promemoria': ['com.samsung.android.app.reminder/com.samsung.android.app.reminder.ui.LaunchMainActivity'],
    'penup': ['com.samsung.android.app.sketchbook/com.samsung.android.app.sketchbook.application.DrawingActivity'],
    'samsung_free': ['com.samsung.android.app.spage/com.samsung.android.app.spage.main.LauncherActivity'],
    'suggerimenti': ['com.samsung.android.app.tips/com.samsung.android.app.tips.TipsMainActivity'],
    'galaxy_wearable': ['com.samsung.android.app.watchmanager/com.samsung.android.app.watchmanager.setupwizard.SetupWizardWelcomeActivity'],
    'bixby': ['com.samsung.android.bixby.agent/com.samsung.android.bixby.assistanthome.AssistantHomeLauncherActivity'],
    'game_launcher': ['com.samsung.android.game.gamehome/com.samsung.android.game.gamehome.app.MainActivity'],
    'good_lock': ['com.samsung.android.goodlock/com.samsung.android.goodlock.MainActivity'],
    'samsung_cloud': ['com.samsung.android.scloud/com.samsung.android.scloud.app.ui.splash.launcher'],
    'theme_park': ['com.samsung.android.themedesigner/com.samsung.android.themedesigner.ui.view.SplashComposeActivity'],
    'samsung_tv_plus': ['com.samsung.android.tvplus/com.samsung.android.tvplus.MainActivity'],
    'samsung_members': ['com.samsung.android.voc/com.samsung.android.voc.LauncherActivity'],
    'cartella_sicura': ['com.samsung.knox.securefolder/com.samsung.knox.securefolder.presentation.switcher.view.SecureFolderShortcutActivity'],
    'smart_switch': ['com.sec.android.easyMover/com.sec.android.easyMover.ui.launch.LauncherActivity'],
    'shazam': ['com.shazam.android/com.shazam.android.activities.SplashActivity'],
    'snapchat': ['com.snapchat.android/com.snapchat.android.LandingPageActivity'],
    'tiktok_studio': ['com.ss.android.tt.creator/com.ss.android.ugc.aweme.splash.SplashActivity'],
    'tripadvisor': ['com.tripadvisor.tripadvisor/com.tripadvisor.android.ui.launcher.LauncherActivity'],
    'smart_life': ['com.tuya.smartlife/com.smart.ThingSplashActivity'],
    'wallapop': ['com.wallapop/com.wallapop.activities.HomeActivity'],
    'shein': ['com.zzkko/com.shein.welcome.WelcomeActivity'],
    'vinted': ['fr.vinted/com.vinted.feature.shell.MDActivity'],
    'inps': ['it.inps.mobile.app.servizi.activity/it.inps.mobile.app.home.activity.SplashScreenActivity'],
    'raiplay': ['it.rainet/it.rainet.ui.splash.SplashActivity'],
    'ticketone': ['it.ticketone.mobile.app.Android/mobile.app.Android.activity.StartupActivity'],
    'unieuro': ['it.unieuro.unieuro/it.unieuro.unieuro.MainActivity'],
    'ho_mobile': ['it.homobile.ho/it.nttdata.vodafonelean.splash.SplashActivity'],
    'q8': ['it.q8.app.clubq8/it.starq8.q8.app.MainActivity'],
    'easypark': ['net.easypark.android/net.easypark.android.mvp.splash.SplashActivity'],
    'vlc': ['org.videolan.vlc/org.videolan.vlc.StartActivity'],
    'speedtest': ['org.zwanoo.android.speedtest/com.ookla.mobile4.screens.main.MainActivity'],
    'posteid': ['posteitaliane.posteapp.appposteid/posteitaliane.posteapp.appposteid.welcome.WelcomeAct'],
    'telepass': ['uk.co.novaware.telepass.android/it.telepass.appunica.SplashScreenActivity'],
    'zepp': ['com.huami.watch.hmwatchmanager/com.xiaomi.hm.health.activity.StartUpActivity'],
    'dashlane': ['com.dashlane/com.dashlane.DashlaneNormalIconActivity'],
    'shop': ['com.shopify.arrive/com.shopify.arrive.MainActivity'],
    'cisalfa': ['it.cisalfasport.mobileapp/com.example.cs_consumer_app.MainActivityProd'],
    'github': ['com.github.android/com.github.android.main.MainActivity'],
}
